---
repos:
  - repo: local
    hooks:
      - id: ansible-lint
        name: ansible-lint
        entry: ansible-lint
        language: python
        files: \.(yaml|yml)$
  - repo: local
    hooks:
      - id: yamllint
        name: yamllint
        entry: yamllint
        language: python
        types: [file, yaml]
