---
- hosts: [all]
  tasks:
    - name: Example from an Ansible Playbook
      ansible.windows.win_ping:

    - name: Change the hostname to "{{ hostname }}"
      win_hostname:
        name: "{{ hostname }}"
      register: res

    - name: Reboot
      win_reboot:
      when: res.reboot_required

    - name: Set timezone to 'Tokyo Standard Time' (GMT+09:00)
      community.windows.win_timezone:
        timezone: Tokyo Standard Time

    - name: Set format, location and unicode to Japanese and copy settings, reboot if required
      community.windows.win_region:
        location: 122
        format: ja-JP
        unicode_language: ja-JP
      register: result

    - name: Reboot
      ansible.windows.win_reboot:
      when: result.restart_required
